name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm run test:unit

    - name: Display SoftUni Username
      run: echo HeliXs66
  
  run-ui-tests:
    needs: build-and-unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install playwright browsers
      run: npx playwright install

    - name: Start application
      run: npm start &

    - name: Run UI tests
      run: npm run test:ui
